"""
Error code constants.

Centralized error codes for consistent error handling.
"""

# Generic errors
INTERNAL_ERROR = "INTERNAL_ERROR"
UNKNOWN_ERROR = "UNKNOWN_ERROR"

# Validation errors
VALIDATION_ERROR = "VALIDATION_ERROR"
INVALID_INPUT = "INVALID_INPUT"
MISSING_FIELD = "MISSING_FIELD"
INVALID_FORMAT = "INVALID_FORMAT"

# Not found errors
NOT_FOUND = "NOT_FOUND"
RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"

# Configuration errors
CONFIGURATION_ERROR = "CONFIGURATION_ERROR"
MISSING_CONFIG = "MISSING_CONFIG"
INVALID_CONFIG = "INVALID_CONFIG"

# Infrastructure errors
INFRASTRUCTURE_ERROR = "INFRASTRUCTURE_ERROR"
DATABASE_ERROR = "DATABASE_ERROR"
FILE_SYSTEM_ERROR = "FILE_SYSTEM_ERROR"
NETWORK_ERROR = "NETWORK_ERROR"

# External service errors
EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR"
LLM_ERROR = "LLM_ERROR"
EMBEDDING_ERROR = "EMBEDDING_ERROR"
API_ERROR = "API_ERROR"

# Timeout errors
TIMEOUT_ERROR = "TIMEOUT_ERROR"
REQUEST_TIMEOUT = "REQUEST_TIMEOUT"
OPERATION_TIMEOUT = "OPERATION_TIMEOUT"

# Authentication errors
UNAUTHORIZED = "UNAUTHORIZED"
INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
MISSING_CREDENTIALS = "MISSING_CREDENTIALS"
EXPIRED_TOKEN = "EXPIRED_TOKEN"

# Authorization errors
FORBIDDEN = "FORBIDDEN"
INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS"
ACCESS_DENIED = "ACCESS_DENIED"

# Rate limiting
RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
QUOTA_EXCEEDED = "QUOTA_EXCEEDED"
